# src/bot/states.py

from enum import IntEnum

class State(IntEnum):
    START = 0
    AWAITING_CONTACT = 1
    AWAITING_VERIFICATION = 2
    AWAITING_TERMS = 3
    MAIN_MENU = 4
    AWAITING_INVESTMENT = 5
    AWAITING_SPORT_SELECTION = 6
    AWAITING_DRAW_OPTION = 7
    AWAITING_TAX_CHOICE = 8
    AWAITING_TAX_TYPE = 9
    AWAITING_TAX_PERCENTAGE = 10
    AWAITING_BOOKMAKER_CHOICE = 11
    AWAITING_HOME_ODDS = 12
    AWAITING_HOME_COMMISSION = 13
    AWAITING_HOME_DEPOSIT = 14
    AWAITING_HOME_WITHDRAWAL = 15
    AWAITING_AWAY_ODDS = 16
    AWAITING_AWAY_COMMISSION = 17
    AWAITING_AWAY_DEPOSIT = 18
    AWAITING_AWAY_WITHDRAWAL = 19
    AWAITING_DRAW_ODDS = 20
    AWAITING_DRAW_COMMISSION = 21
    AWAITING_DRAW_DEPOSIT = 22
    AWAITING_DRAW_WITHDRAWAL = 23
    AWAITING_CALCULATION = 24
    ADMIN_MODE = 25
    AWAITING_CUSTOM_INVESTMENT = 26
    AWAITING_ODDS_SPORT_SELECTION = 27
    ADMIN_AWAITING_BROADCAST = 100  # State for waiting for broadcast message input
    ADMIN_AWAITING_BROADCAST_CONFIRM = 101  # State for waiting for broadcast confirmation
    ADMIN_AWAITING_PREMIUM_ACTION = 102  # State for waiting for premium action selection
    ADMIN_AWAITING_USER_ID = 103  # State for waiting for user ID input for premium management
    ADMIN_AWAITING_PREMIUM_DAYS = 104  # State for waiting for the number of days for premium access